### ISSUE TITLE
Missions start and tp me the second I join.

### ISSUE THREAD

**Issue by iGrizion** [ddraigcymraeg/mrp-missions#8]
self hosting a server for splitscreen, whenever i join it tps me and starts a mission, or just starts mission, i set extra time to wait to 999, set some of the stuff to false and it stills starts mission when i join, what am i doing wrong?

**Comment by ddraigcymraeg** [comment]
you can just use the /stop command to stop a mission. 

but 2 things to try/do in the code: 
in server.lua 
make theExtraTime.... variable large  
and change this line: 

		_if (not ActiveMission and not blInSpaceTime and ((tick) >= TimeLeft)) and doPlayersExist() then_

change to 
		_if (not ActiveMission and not blInSpaceTime and ((tick) >= TimeLeft)) and doPlayersExist() and blMadeIt then_

then in client.ua for the _playerSpawned_ event handler
remove both occurrences of: 
_TriggerServerEvent("sv:checkmission",true)_
as well as the associated print statement.

the server.lua change _may_ affect auto mission rotation, not sure. 

if all that doesnt work and you dont want to use the stop command, you will need to dig into the code more to tweak it how you like.

**Comment by ddraigcymraeg** [comment]
meant to say comment out both occurrences of  TriggerServerEvent("sv:checkmission",true)
