### ISSUE TITLE
Cant get wanted after completing a mission

### ISSUE THREAD

**Issue by iGrizion** [ddraigcymraeg/mrp-missions#9]
Cant get any wanted level after completing a mission, or stopping a mission.

**Comment by ddraigcymraeg** [comment]
you can remove the code below at the bottom that removes wanted level from client.lua, but you may or will get wanted during mission.
--remove wanted level
Citizen.CreateThread(function()

   for i = 1, 32 do
        Citizen.InvokeNative(0xDC0F817884CDD856, i, false)
    end
    while true do
        Citizen.Wait(0)
        if GetPlayerWantedLevel(PlayerId()) ~= 0 then
            ClearPlayerWantedLevel(PlayerId())
        end
    end
	
end)

Probably better: You can probably put in a mission check around 
 _Citizen.InvokeNative(0xDC0F817884CDD856, i, false)_
and 
_ClearPlayerWantedLevel(PlayerId())_ 
lines like so:
_if Active == 1 and MissionName ~="N/A" then_

_end_

for example this should only remove wanted level during a mission for all players. If you are using optin/optout variables, you would also need to check for the decor value on the player as well for either of these, to find players that are actually in the mission.
Citizen.CreateThread(function()

   for i = 1, 32 do
       if Active == 1 and MissionName ~="N/A" then
        Citizen.InvokeNative(0xDC0F817884CDD856, i, false)
      end
    end
    while true do
        Citizen.Wait(0)
        if GetPlayerWantedLevel(PlayerId()) ~= 0 then
           if Active == 1 and MissionName ~="N/A" then
            ClearPlayerWantedLevel(PlayerId())
           end
        end
    end
	
end)

**Comment by ddraigcymraeg** [comment]
play around with that code section.
